# Generated by Django 4.2.2 on 2023-06-24 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Record Title', max_length=50, verbose_name='Record Title')),
                ('description', models.TextField(help_text='Enter Record Description', verbose_name='Record Description')),
                ('type', models.CharField(choices=[('THES', 'THESIS'), ('DATA', 'DATASET'), ('PUBL', 'PUBLICATION'), ('NTRO', 'NON-TRADITIONAL RESEARCH OUTPUT')], help_text='Enter Record Type', max_length=4, verbose_name='Record Type')),
                ('rating', models.IntegerField(blank=True, default=None, help_text='Enter Rating (1-10)', null=True)),
                ('version', models.FloatField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
