# Generated by Django 4.2.2 on 2023-06-29 22:51

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-updated'], 'permissions': (('can_view_record', 'Can view record'),)},
        ),
        migrations.AlterField(
            model_name='record',
            name='rating',
            field=models.IntegerField(blank=True, default=None, help_text='Enter Rating (1-10)', null=True),
        ),
    ]
