# Generated by Django 4.2.2 on 2023-06-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_options_alter_record_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-updated'], 'permissions': (('can_bla_record', 'Can bla record'),)},
        ),
    ]
