# Generated by Django 4.2.2 on 2023-06-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-updated']},
        ),
    ]
