# Generated by Django 4.2.2 on 2023-06-30 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Enter Rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('THES', 'Thesis'), ('DATA', 'Dataset'), ('PUBL', 'Publication'), ('SOFT', 'Software'), ('NTRO', 'NTRO')], help_text='Enter Record Type', max_length=4, verbose_name='Record Type'),
        ),
    ]
