# Generated by Django 4.2.2 on 2023-06-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_recordfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordFile',
            new_name='File',
        ),
    ]
