# Generated by Django 4.2.2 on 2023-07-10 05:38

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_rename_recordfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Enter Rating (1-10)', null=True, validators=[records.models.validate_record_rating_1_10]),
        ),
    ]
