# Generated by Django 4.2.2 on 2023-07-10 05:43

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_record_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('THES', 'Thesis'), ('DATA', 'Dataset'), ('PUBL', 'Publication'), ('SOFT', 'Software'), ('NTRO', 'NTRO')], help_text='Enter Record Type', max_length=4, validators=[records.models.validate_type], verbose_name='Record Type'),
        ),
    ]
