# Generated by Django 4.2.2 on 2023-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_record_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-updated'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-updated'], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, help_text='Enter File Details', max_length=100, null=True),
        ),
    ]
