# Generated by Django 4.2.3 on 2023-08-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_file_options_alter_record_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='RecordFile',
        ),
        migrations.AlterModelOptions(
            name='recordfile',
            options={'ordering': ['-updated'], 'verbose_name': 'Record File', 'verbose_name_plural': 'Record Files'},
        ),
    ]
